-- JFT-Basic Practice — Supabase setup for Global Chat media
-- Run this in Supabase SQL Editor after backing up your existing schema.
-- The current app uses a custom login table ("Jft-Basic"), not Supabase Auth.
-- Therefore Storage policies below intentionally use public access for compatibility;
-- do NOT put a Supabase service-role key in the browser.

alter table public.global_chats add column if not exists message_type text not null default 'text';
alter table public.global_chats add column if not exists file_url text;
alter table public.global_chats add column if not exists file_path text;
alter table public.global_chats add column if not exists file_name text;
alter table public.global_chats add column if not exists mime_type text;
alter table public.global_chats add column if not exists file_size bigint;
alter table public.global_chats add column if not exists duration_seconds numeric;

create index if not exists global_chats_message_type_idx on public.global_chats(message_type);

-- Storage bucket: 25 MB per file, common chat media/file types.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'chat-media',
  'chat-media',
  true,
  26214400,
  null
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = null;

-- The existing custom-auth application has no auth.jwt() identity to enforce in Storage.
-- Restrict object paths to the chat/ prefix, but allow public read/upload for compatibility.
drop policy if exists "JFT chat media public read" on storage.objects;
create policy "JFT chat media public read"
on storage.objects for select to public
using (bucket_id = 'chat-media' and (storage.foldername(name))[1] = 'chat');

drop policy if exists "JFT chat media public upload" on storage.objects;
create policy "JFT chat media public upload"
on storage.objects for insert to public
with check (bucket_id = 'chat-media' and (storage.foldername(name))[1] = 'chat');

drop policy if exists "JFT chat media public delete" on storage.objects;
create policy "JFT chat media public delete"
on storage.objects for delete to public
using (bucket_id = 'chat-media' and (storage.foldername(name))[1] = 'chat');

-- ===== Global Chat: mentions / notifications / admin announcements =====
create table if not exists public.chat_notifications (
  id bigint generated by default as identity primary key,
  recipient_id text not null,
  recipient_name text,
  sender_id text,
  sender_name text,
  message_id text,
  type text not null default 'mention',
  content text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists chat_notifications_recipient_unread_idx
  on public.chat_notifications(recipient_id, read_at, created_at desc);

create table if not exists public.chat_announcements (
  id bigint generated by default as identity primary key,
  admin_id text not null,
  admin_name text not null,
  title text not null default 'Pengumuman Admin',
  message text not null default '',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  file_url text,
  file_path text,
  file_name text,
  mime_type text,
  file_size bigint,
  media_type text,
  media_mode text not null default 'video',
  duration_seconds numeric
);

alter table public.chat_announcements add column if not exists title text not null default 'Pengumuman Admin';
alter table public.chat_announcements add column if not exists message text not null default '';
alter table public.chat_announcements add column if not exists file_url text;
alter table public.chat_announcements add column if not exists file_path text;
alter table public.chat_announcements add column if not exists file_name text;
alter table public.chat_announcements add column if not exists mime_type text;
alter table public.chat_announcements add column if not exists file_size bigint;
alter table public.chat_announcements add column if not exists media_type text;
alter table public.chat_announcements add column if not exists media_mode text not null default 'video';
alter table public.chat_announcements add column if not exists duration_seconds numeric;
create index if not exists chat_announcements_expiry_idx
  on public.chat_announcements(expires_at desc);
create index if not exists chat_announcements_created_idx
  on public.chat_announcements(created_at desc);

create table if not exists public.announcement_reads (
  announcement_id bigint not null references public.chat_announcements(id) on delete cascade,
  reader_id text not null,
  read_at timestamptz not null default now(),
  primary key (announcement_id, reader_id)
);

alter table public.chat_notifications enable row level security;
alter table public.chat_announcements enable row level security;
alter table public.announcement_reads enable row level security;

drop policy if exists "JFT chat notifications public read" on public.chat_notifications;
create policy "JFT chat notifications public read" on public.chat_notifications for select to public using (true);
drop policy if exists "JFT chat notifications public insert" on public.chat_notifications;
create policy "JFT chat notifications public insert" on public.chat_notifications for insert to public with check (true);
drop policy if exists "JFT chat notifications public update" on public.chat_notifications;
create policy "JFT chat notifications public update" on public.chat_notifications for update to public using (true) with check (true);
drop policy if exists "JFT chat notifications public delete" on public.chat_notifications;
create policy "JFT chat notifications public delete" on public.chat_notifications for delete to public using (true);

drop policy if exists "JFT announcements public read" on public.chat_announcements;
create policy "JFT announcements public read" on public.chat_announcements for select to public using (true);
drop policy if exists "JFT announcements public insert" on public.chat_announcements;
create policy "JFT announcements public insert" on public.chat_announcements for insert to public with check (true);
drop policy if exists "JFT announcements public delete" on public.chat_announcements;
create policy "JFT announcements public delete" on public.chat_announcements for delete to public using (true);

drop policy if exists "JFT announcement reads public read" on public.announcement_reads;
create policy "JFT announcement reads public read" on public.announcement_reads for select to public using (true);
drop policy if exists "JFT announcement reads public insert" on public.announcement_reads;
create policy "JFT announcement reads public insert" on public.announcement_reads for insert to public with check (true);
drop policy if exists "JFT announcement reads public update" on public.announcement_reads;
create policy "JFT announcement reads public update" on public.announcement_reads for update to public using (true) with check (true);

do $$
begin
  alter publication supabase_realtime add table public.chat_notifications;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.chat_announcements;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.global_chats;
exception when duplicate_object then null;
end $$;
